### ISSUE TITLE
Find links API

### ISSUE THREAD

**Issue by snarfed** [aaronpk/Telegraph#2]
it'd be great to add Find Links to the API! especially with a target domain param that would make it send webmentions from the source page to all of its links to a given domain.

[discussion from IRC](http://indiewebcamp.com/irc/2016-01-09#t1452385516325):

> snarfed: just to confirm, the find links part doesn't have an api right now, right?
> ...
> aaronpk: oh yeah haha it'd be super trivial to add, since right now the "dashboard" page makes an ajax call to find the links so it's actually already returning it as JSON in a separate route
> snarfed: nice! my use case is, I'd like to give it a source page and a target domain, and have it send wms to every link on that domain
> snarfed: with that, i could implement https://snarfed.org/global-webmention-service with zero code
> snarfed: just superfeedr -> zapier -> telegraph
> snarfed: i think
> aaronpk: oh! interesting!
> aaronpk: I made the UI have buttons to send a webmention for each link found on the page because from what i've seen in practice you don't actually want to webmention *every* link on the page, just some of them.
> aaronpk: but adding the constraint of every link on a given domain seems reasonable!

**Comment by snarfed** [comment]
hey @aaronpk, think this would be appropriate for me to tackle using the existing route and send as a PR? or would you want to do it yourself?

**Comment by aaronpk** [comment]
hm, I suppose the web interface could be updated to use the API route (without authentication) so it would be a matter of making sure the current route doesn't require auth. You are welcome to take a stab at this. I am not likely to get to this over the weekend since I'm still pushing forward on launching my site.

**Comment by snarfed** [comment]
starting to look at this, and i figured i'd run concrete proposals by you before i start coding.

to do https://snarfed.org/global-webmention-service , i'd need a single endpoint that both finds links to a given target domain and enqueues wms for them. i was thinking of just making `/webmention` accept either `target` _or_ `target_domain`. the catch is, it would need to return multiple status URLs, one for each wm, which isn't really backward compatible. or it could just not return them, but right now the docs don't say status URL is optional. (it'd also need to hit the user's callback once for each wm, but that's a doable implementation detail.)

an alternative would be a new `/find-links` endpoint that optionally also enqueues wms. maybe less elegant; i don't kmow.

thoughts? it's early days for telegraph, maybe we don't need to prioritize strict backward compatibility too highly yet if we're still iterating on the API?

not urgent, i know you're busy. :P

**Comment by aaronpk** [comment]
Interesting, this gives me some more ideas.

I think I am leaning towards your first suggestion of changing `/webmention` to also accept a `target_domain` parameter, and including the multiple status URLs. Since it would not involve changing any behavior when the `target` parameter is sent, it actually would be a backwards compatible change.

I think I would want two parse to the response. One URL in the response would have a status page showing all the webmentions that were queued, and it would also include links to the individual webmention status URLs. e.g.:

```
POST /webmention
token=abc123&source=http://example.com/post/100&target_domain=target.example.com

HTTP/1.1 201 Created
Content-type: application/json
Location: https://telegraph.p3k.io/webmentions/BATCH_ID

{
  "status": "queued",
  "location": "https://telegraph.p3k.io/webmentions/BATCH_ID",
  "locations": [
    "https://telegraph.p3k.io/webmention/1000",
    "https://telegraph.p3k.io/webmention/1001",
    "https://telegraph.p3k.io/webmention/1002"
  ]
}
```

**Comment by snarfed** [comment]
sgtm! i'll start on this.

just fyi, the batch status page sounds good, but i'm unlikely to do it in the first pass at least. maybe afterward. let me know if you feel strongly otherwise.

**Comment by aaronpk** [comment]
no problem!

**Comment by snarfed** [comment]
tentatively closing. thanks for the merges @aaronpk!
