### ISSUE TITLE
Only showing links from first mf2 object on page

### ISSUE THREAD

**Issue by keithjgrant** [aaronpk/Telegraph#24]
I have a design with two top-level mf2 objects: an h-card followed by an h-entry (https://keithjgrant.com/posts/2018/shindig/)

When I try to use Telegraph to send webmentions, it only lists links/urls from the h-card, and doesn’t show those from the h-entry.

**Comment by aaronpk** [comment]
Now that XRay can be used as a library, I should really be running the page through XRay since that already includes logic to find the primary object on the page. It looks like XRay already parses your page just fine so this shouldn't be an issue https://xray.p3k.io/parse?url=https%3A%2F%2Fkeithjgrant.com%2Fposts%2F2018%2Fshindig%2F

**Comment by keithjgrant** [comment]
Do you know of another site/tool I can use in the meantime to send WMs? I’ve been using some hacked-together scripts in the meantime, but I keep running into bugs
